apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-hpa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    path: autoscaling
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true