apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-hpa
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    path: autoscaling
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      