name: ArgoCD Sync Application

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'monitoring/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: ArgoCD CLI Login
        run: |
          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure
      - name: Sync Applications
        run: |
          argocd app sync myapp
          argocd app sync monitoring-stack
        env:
          ARGOCD_SERVER: argocd.example.com
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
