apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: myapp-dev
  annotations:
    sops.io/encrypted: "true"
type: Opaque
data:
  DATABASE_URL: ENC[AES256_GCM,data:...,type:str]
  REDIS_URL: ENC[AES256_GCM,data:...,type:str]